---
- name: Copy zabbix-conf files for monitoring
  hosts: local
  remote_user: puzerkin

  tasks:
    - name: get ubuntu version
      ansible.builtin.shell: zabbix_agentd -t ubuntu.version

    - name: get nginx version
      ansible.builtin.shell: zabbix_agentd -t nginx.version
